spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: root
    password: 1234
  h2:
    console:
      enabled: true
